version: '3'
services:
  app:
    container_name: vinijrblog
    build:
      context: ../
      dockerfile: deployments/Dockerfile
    volumes:
      - "../app/:/var/www/html"
    ports:
      - 10004:80
