version: "2"
services:
  app:
    container_name: app-a8 
    build:
      context: ../
      dockerfile: deployments/Dockerfile
    volumes:
      - "../app/:/app"
    ports:
      - "5000:5000"
      - "9051:9051"
    networks: 
      - a8_net
    restart: always
    environment:
      KEY: secret

networks:
  a8_net: