version: "2"

services:
   app:
      container_name: app-a10
      build:
         context: ../
         dockerfile: deployments/Dockerfile
      ports:
         - "10010:10010"
      environment:
         SECRET_KEY: secretkey
         MYSQL_ENDPOINT: mysqldb-a10
         MYSQL_PASSWORD: pass
         MYSQL_USER: user
         MYSQL_DB: A10
      networks:
         - a10_net
      depends_on:
         - mysqldb-a10
      external_links:
         - mysqldb-a10:mysqldb-10
      volumes:
         - "../app/:/app"
      restart: always

   mysqldb-a10:
      container_name: mysqldb-a10
      image: mysql:5.7
      ports:
         - "3307:3307"
      environment:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_DATABASE: A10
         MYSQL_USER: user
         MYSQL_PASSWORD: pass
      networks:
         - a10_net
      volumes:
         - storage-a10-database:/var/lib/mysql
      restart: unless-stopped

volumes:
   storage-a10-database:

networks:
   a10_net:
