version: '3'

networks:
    insecure_net:

volumes:
    mongo_vol:

services:
    api:
        container_name: a2_insecure_api
        build:
            context: ../
            dockerfile: deployments/api.Dockerfile
        ports:
            - "9999:9999"
        networks:
            - insecure_net
        command: "go run main.go"
        depends_on:
            - mongodb
        external_links:
            - mongodb:mongodb
        environment:
            MONGO_HOST: mongodb
            MONGO_DATABASE_NAME: insecure_go_project
            MONGO_DATABASE_USERNAME: ${MONGO_DATABASE_USERNAME}
            MONGO_DATABASE_PASSWORD: ${MONGO_DATABASE_PASSWORD}

    mongodb:
        container_name: mongodb
        build:
            context: ../
            dockerfile: deployments/mongo.Dockerfile
        ports:
          - "27017:27017"
          - "27018:27018"
        volumes:
            - mongo_vol:/data/db
        networks:
            - insecure_net
        environment:
            MONGO_HOST: mongodb
            MONGO_DATABASE_NAME: insecure_go_project
            MONGO_DATABASE_USERNAME: ${MONGO_DATABASE_USERNAME}
            MONGO_DATABASE_PASSWORD: ${MONGO_DATABASE_PASSWORD}