version: '3'

networks:
    insecure_net:

volumes:
    mongo_vol:

services:
    api:
        container_name: a2_insecure_api
        build:
            context: ../
            dockerfile: deployments/api.Dockerfile
        ports:
            - "9999:9999"
        networks:
            - insecure_net
        command: "go run main.go"
        depends_on:
            - mongodb
        external_links:
            - mongodb:mongodb
        environment:
            - MONGO_USER
            - MONGO_PASS
            - MONGO_ROLES
            - MONGO_DB

    mongodb:
        container_name: mongodb
        build:
            context: ../
            dockerfile: deployments/mongo.Dockerfile
        ports:
          - "27017:27017"
          - "27018:27018"
        volumes:
            - mongo_vol:/data/db
        networks:
            - insecure_net
        environment:
            MONGO_DB: ${MONGO_DB}
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
