version: '3.8'

services:
  drupal:
    image: drupal:7.74
    container_name: drupal
    environment:
      POSTGRES_PASSWORD: example
    build:
      context: ../
      dockerfile: deployments/drupal.Dockerfile
    ports:
      - 80:80
    volumes:
      - ../app/html:/var/www/html
    restart: always
    networks: 
      - a9_net

  db:
    image: postgres:latest
    container_name: a9db
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    networks: 
      - a9_net
    volumes:
      - db_data:/var/lib/postgresql/data
      - ../app/dump.db:/docker-entrypoint-initdb.d/dump.sql

volumes:
  db_data:

networks: 
  a9_net:
